// Retire drafts produced by an older generation contract.
//
// gen_meta.prompt_version records what produced a draft. When the contract
// changes in a way that makes older drafts unlike anything we would generate
// now — R1.6's response_mode and answer_format could not be returned at all
// before v12 — the pending queue should be regenerated rather than reviewed.
// Approved questions are never touched: they are in use and were honest under
// the contract that made them.
//
// Run: pnpm tsx scripts/retire-stale-drafts.ts --yes [--keep v12]
import 'dotenv/config';
import { dbConnect, Question } from '@/lib/db';
import { PROMPT_VERSION } from '@/lib/prompts/question-gen';

async function main() {
  const argv = process.argv.slice(2);
  const keepAt = argv.indexOf('--keep');
  const keep = keepAt >= 0 ? argv[keepAt + 1] : PROMPT_VERSION;

  if (!argv.includes('--yes')) {
    const stale = await countStale(keep);
    console.log(`Would retire ${stale} draft(s) not generated by ${keep}. Re-run with --yes.`);
    process.exit(0);
  }

  await dbConnect();
  const res = await Question.updateMany(
    { status: 'draft', 'gen_meta.prompt_version': { $ne: keep } },
    { $set: { status: 'retired', reject_reason: `stale-contract-pre-${keep}` } },
  );
  console.log(`Retired ${res.modifiedCount} draft(s) from contracts older than ${keep}.`);
  console.log(`Drafts remaining: ${await Question.countDocuments({ status: 'draft' })}`);
  process.exit(0);
}

async function countStale(keep: string): Promise<number> {
  await dbConnect();
  return Question.countDocuments({ status: 'draft', 'gen_meta.prompt_version': { $ne: keep } });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
